### ISSUE TITLE
cannot open include file 'syscalls.h': no such file or directoy 

### ISSUE THREAD

**Issue by DarknightCanada** [georgesotiriadis/Chimera#10]
cannot open include file 'syscalls.h': no such file or directory 
I included it both as Additional Include Directories and also absolute patch still same error! anyone else had the same issue?
<img width="1500" alt="Screenshot 2023-09-03 at 10 01 11 PM" src="https://github.com/georgesotiriadis/Chimera/assets/65374001/e0344766-ef91-454e-9c36-e4b788bfa1ae">

**Comment by radman404** [comment]
you need to change the path in both main.cpp and syscalls.c to ".header_Images\syscalls.h" or at least this is what worked for myself.

**Comment by georgesotiriadis** [comment]
everything is fixed in version 1.0 checkout the updates.
