### ISSUE TITLE
fatal error LNK1107: invalid or corrupt file: cannot read at 0xCE0

### ISSUE THREAD

**Issue by ydy4** [georgesotiriadis/Chimera#9]
basically after importing the syscalls.h header file and building the project I get the following error 
![image](https://github.com/georgesotiriadis/Chimera/assets/95150458/8e3fceac-a4a8-4a26-8b57-95b92600d85f)

**Comment by georgesotiriadis** [comment]
first of all did you changed the project to a dll? second download the following repo which i made some updates to syswhispers3 replace the files with the new files that are located in the header_files folder & in chimera_automation folder. also run the updated tool again to produce new code. Tell if it worked

https://github.com/georgesotiriadis/Chimera/tree/sys3

**Comment by ydy4** [comment]
ok just changed the project to dll and no more error thanks
